### ISSUE TITLE
No publish

### ISSUE THREAD

**Issue by VineyAT** [Fred07/go-service-template-hands-up#1]
https://github.com/Fred07/go-service-template-hands-up/blob/a110c2a4eba2fb34b5fdc3c4f19ad19b0e0c78fe/localcache/impl.go#L8

以我的認知，這個應該是不會給外部修改得到，可以把它改成小寫。另外就是 golang 的命名規則是駝峰的，你的這個命名規則比較接近 python or c/c++

**Comment by Fred07** [comment]
ok~ fix in 3b32192
