### ISSUE TITLE
assert and compare whole structure

### ISSUE THREAD

**Issue by VineyAT** [Fred07/go-service-template-hands-up#3]
https://github.com/Fred07/go-service-template-hands-up/blob/a110c2a4eba2fb34b5fdc3c4f19ad19b0e0c78fe/localcache/impl_test.go#L50

這邊比較值的地方沒有問題，但是對於 cache 而言他還有包含過期時間的部分，建議可以一起比對，用的方法可以參考

Code:
https://github.com/AmazingTalker/at-tracking/blob/e0ba531413f177742d0258a38c8c176dc8e7d945/pkg/fbads/impl.go#L16
unit test: 
https://github.com/AmazingTalker/at-tracking/blob/e0ba531413f177742d0258a38c8c176dc8e7d945/pkg/fbads/impl_test.go#L33

**Comment by Fred07** [comment]
nice~

fixed in  3c438ab
